site_name: Real-Time Voice Agent Documentation
site_description: Azure-powered real-time voice agent with text-to-speech and speech recognition capabilities
# site_url: https://github.com/Azure-Samples/art-voice-agent-accelerator/
repo_url: https://github.com/Azure-Samples/art-voice-agent-accelerator/
repo_name: Azure-Samples/art-voice-agent-accelerator

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mermaid2
  - neoteroi.mkdocsoad
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            merge_init_into_class: true
            docstring_section_style: table
            members_order: source
            group_by_category: true
            show_category_heading: true

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start Guide: getting-started/README.md
    - Local Development: getting-started/local-development.md
    - Configuration Guide: getting-started/configuration.md
  - Architecture:
    - Overview: architecture/README.md
    - LLM Orchestration: architecture/llm-orchestration.md
    - Data Flows: architecture/data-flows.md
    - Integrations: architecture/integrations.md
    - ACS Flows: architecture/acs-flows.md
  - Deployment:
    - Deployment Guide: deployment/README.md
    - Production: deployment/production.md
    - CI/CD: deployment/cicd.md
  - Security:
    - Authentication: security/authentication.md
  - Operations:
    - Monitoring: operations/monitoring.md
    - Troubleshooting: operations/troubleshooting.md
    - Testing: operations/testing.md
    - Load Testing: operations/load-testing.md
  - API Reference:
    - Overview: api/README.md
    - API Reference: api/api-reference.md
  - Industry Solutions:
    - Healthcare: industry/healthcare.md
  - Samples & Labs:
    - Overview: samples/README.md
  - Reference:
    - Overview: reference/README.md
    - Repository Structure: reference/repository-structure.md
    - Speech Recognition: reference/speech-recognition.md
    - Speech Synthesis: reference/speech-synthesis.md
    - Streaming Modes: reference/streaming-modes.md
    - Utilities: reference/utilities.md
extra_css:
  - assets/oad-styles.css
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
      baselevel: 2
