name: Deploy Documentation

on:
  push:
    branches:
      - main
      - feature/mkdocs-v2
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements-docs.txt'
      - '.github/workflows/docs.yml'
  workflow_dispatch:
# Permissions for GitHub Actions deployment
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'

  #     - name: Install documentation dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements-docs.txt

  #     - name: Install minimal project dependencies
  #       run: |
  #         pip install fastapi pydantic uvicorn starlette
  #       continue-on-error: true

  #     - name: Setup Pages
  #       id: pages
  #       uses: actions/configure-pages@v4

  #     - name: Build documentation
  #       run: |
  #         mkdocs build --clean --strict
  #         touch ./site/.nojekyll
  #       env:
  #         AZURE_SPEECH_KEY: "dummy-key-for-docs"
  #         AZURE_SPEECH_REGION: "eastus"

  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: ./site

  deploy:
    # if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    # needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: requirements-docs.txt